### ISSUE TITLE
Please add the demo

### ISSUE THREAD

**Issue by sajera** [custom-select/custom-select#16]

**Comment by sajera** [comment]
It can be some think simple.
For example plunker
https://plnkr.co/edit/8dmDq3lgLwTfnwR9TI5p?p=preview

**Comment by marconucara** [comment]
Thank you for your suggestion. You are right, we will deal with it very soon.

**Comment by gionatan-lombardi** [comment]
Hi @sajera 
with Pull Request #21 we've added demos for every example with [codesandbox.io](https://codesandbox.io/).
Thanx a lot for your support and suggestion.
