### ISSUE TITLE
Re-render panel with current <select> state

### ISSUE THREAD

**Issue by pjordaan** [custom-select/custom-select#17]
Hi, I'm trying to make a custom dropdown in Angular, and I'm running in the problem with syncing the native select with the custom panel. The Angular template engine creates/updates the select and option, but then I run in to the trouble in updating the custom panel.

I tried several things
- If I only run customSelect once, I get an empty dropdown because of order of execution and option not being added yet.
- if I run customSelect on every template update, the select keeps being decorated with the custom dropdown until my browser crashes...
- If I try to empty and rebuild it, I end up with no option selected or the error parentNode not found. I also have trouble updating the select when the select is open.
- If I try to only add options if they have no property customSelectCstOption I do add new options if they are added, but it's a hack and the order is incorrect.

So what is the correct solution to update the custom selection if the native select is being updated outside this library?

**Comment by marconucara** [comment]
Hi,
you should create an empty customSelect once, the you should use the custom select method for [append](https://github.com/custom-select/custom-select#appendelements-target-method)/[remove ](https://github.com/custom-select/custom-select#removenode-method) options. You shouldn't use the same model for trigger this add/remove functions and custom select update for avoid infinite cycles of `model change -> add/remove -> model change`.

If you need to check if an option is in the customSelect you can check if it's in the cstSel.select.options array. But rember, you should add options only with custom select method, not using ng-repeat on original options.

I hope it's clear, I don't know the exact methods in angular (which version by the way?)

**Comment by pjordaan** [comment]
using the new Angular 2.0+, but yeah, I was afraid this was the case. I was using a lifecycle hook to redecorate it, and let Angular update the template and thus the options inside the native select.
I think I could resort to writing a custom structural Angular directive that calls append/remove of custom-select or maybe look for an alternative that can redecorate the fancy selectbox from the select again.
In my opinion I like this library for being written in vanilla js, but I do miss some sync() method.

**Comment by gionatan-lombardi** [comment]
@pjordaan Hi, sorry for le late response and thanx for the support.

Even if the `custom-select` is used within a framework it needs to be used with the provided API and in the Angular a directive is a good place to get the job done.

After the init process we have our Single Source of Truth inside the library.
Adding a sync method means to have it again outside and then bring it in and map new and old states with diffs and other dirty procedures.
