### ISSUE TITLE
No working With Bootstrap 4 beta 2 css

### ISSUE THREAD

**Issue by ztvMark** [custom-select/custom-select#22]
Only work with bootstrap 4 alpha example

`
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

	<link rel="stylesheet" href="css/custom-select.css">

	<style type="text/css">
		.dropdown-optgroup {
			border-top: 1px solid #e5e5e5;
			margin-top: 6px;
			padding-top: 6px;
			padding-bottom: 6px;
		}
		.dropdown-optgroup::before {
			content: attr(data-label);
			display: block;
			padding: 3px 20px;
			font-weight: bold;
		}
		.dropdown-item {
			cursor: pointer;
		}
	</style>

</head>
<body>

	<label for="mySelect2">Select with optgroup</label>
	<select id="mySelect2">
		<option value>Select...</option>
		<optgroup label="Cips">
			<option value="zizz">Zizz</option>
		</optgroup>
		<optgroup label="Lips">
			<option value="fruit">mango</option>
			<option value="flower">rose</option>
			<option value="fruit">pineapple</option>
			<option value="flower">lotus</option>
			<option value="flower">lily</option>
			<option value="lorem">Lorem ipsum dolor</option>
		</optgroup>
	</select>

	
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

	<script src="js/custom-select.min.js"></script>

	<script>
		if (typeof require !== 'undefined') {
		  var customSelect = require("custom-select").default;
		  require("css/custom-select.css");
		}
		customSelect('#mySelect2', {
		  openerClass: 'btn btn-info btn-block dropdown-toggle',
		  panelClass: 'dropdown-menu bg_dark w-100',
		  optionClass: 'dropdown-item',
		  optgroupClass: 'dropdown-optgroup',
		  isOpenClass: 'open',
		});
	</script>
</body>
</html>`

if add the https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css fails

**Comment by marconucara** [comment]
They changed dropdown behavior, ranaming the class 'open' to 'show' and moving it to the panel. We can't move the isOpenClass only for boostrap, so I simply suggest you to add this css:

```
.custom-select-container.open .dropdown-menu{
  display: block;
}
