### ISSUE TITLE
Not applied when hidden within a toggled div

### ISSUE THREAD

**Issue by contempoinc** [custom-select/custom-select#23]
Do I need to do a callback or something in order for the custom select to be applied when the inputs are contained within a toggled hide/show type div?

**Comment by gionatan-lombardi** [comment]
Hi @contempoinc, I'm not totally sure what you're asking for. Is your `<select>` contained within a toggled `<div>` and you want to init the custom-select lib only when the `<div>` is shown?

**Comment by contempoinc** [comment]
Thanks for the quick reply! The select is contained within a toggled div, all the other selects within the site work perfectly, just ones within a div that's "hidden" the init isn't called so when that div is toggled open its displaying a standard select and not the custom.

Quick Example Screencast: https://cl.ly/2c0q213x1i0e

**Comment by marconucara** [comment]
I'm not sure about what video should meaning. Some code would be better, what version are you using? JQuery or not? How do you hide the block? 
Anyway your firsts customselect doesn't seems to fully work too (the panel is native). Maybe you could check again our [demos](https://github.com/custom-select/custom-select#demos).

**Comment by marconucara** [comment]
I close it. Feel free to respond to reopen it.
