### ISSUE TITLE
IE11 have two problem

### ISSUE THREAD

**Issue by webestet** [custom-select/custom-select#24]
1) `"TypeError: Unable to get property 'customSelect' of undefined or null reference`
2) `select.addEventListener('change', function(e) {
        console.log(e)
      });`

This code don't work. And event does not come.

**Comment by marconucara** [comment]
Hi,
we probably need some more information here. 

Does it work on other browsers? 

How do you include the library (require/import/download and which path)?

Do you know which lines cause the TypeError? Is it inside the library or is it in your code?

Everything works fine in our [demo](https://github.com/custom-select/custom-select#demos), using ie 11 too.

Finally, if you can share a public link it would be easier to find the issue.

**Comment by marconucara** [comment]
I close it. Feel free to respond to reopen it.

**Comment by webestet** [comment]
Yes, I get answer) Thanks.
