### ISSUE TITLE
Refresh custom select

### ISSUE THREAD

**Issue by xama** [custom-select/custom-select#27]
Hello,
Is there a method or a simple way to refresh the custom select, after updating the select ?

Thanks

**Comment by gionatan-lombardi** [comment]
Hi @xama ,
in a previous issue (#17) we explained the correct way to do it and the reasons behind it.

After the init process don't alter the `select` directly but do it only with the provided API (append, insertBefore, remove, empty).

**Comment by xama** [comment]
@gionatan-lombardi 
Thank you for you help.
